### ISSUE TITLE
Propagate namespace into ingress anotations

### ISSUE THREAD

**Issue by semik** [CZERTAINLY/CZERTAINLY-Helm-Charts#223]
Default content of ingress.annotations is:
```
    nginx.ingress.kubernetes.io/auth-tls-secret: "czertainly/trusted-certificates",
```
this causes failure of deployment in situations where CZERTAINLY is installed somewhere else than into NS named 'czertainly'.

It would be nice to use namespace defined for helm.

**Comment by 3keyroman** [comment]
You can easily change that using [`values.yaml`](https://github.com/CZERTAINLY/CZERTAINLY-Helm-Charts/blob/develop/charts/czertainly/values.yaml#L448). The default is:

```yaml
ingress:
  annotations: {
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP",
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "optional",
    nginx.ingress.kubernetes.io/auth-tls-secret: "czertainly/trusted-certificates",
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "3",
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true",
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
  }
```
